config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: [:destroy] do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end

  get '/mentions', to: 'statuses#mentions'
  resources :statuses do
    member do
      post 'retweet'
    end
  end

  resources :hashtags, only: [:show]
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user, class_name: "User", foreign_key: "mentioned_user"
  belongs_to :status

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :fan, class_name: 'User', foreign_key: "fan_id"
  belongs_to :celebrity, class_name: 'User', foreign_key: 'celebrity_id'

end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :mentions
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :parent_status, foreign_key: 'retweet_id', class_name: 'Status' 


  validates :creator, presence: true
  validates :body, presence: true

  after_save :add_mentions!


  def add_mentions!
    body = self.body
    mentions = body.scan(/@(\w*)/)
    
    if !mentions.empty?
      mentions.each do |mention|
        m = mention.first
        user = User.find_by(username: m)

        if user
          Mention.create(mentioned_user: user.id, status_id: self.id)
        end
      end 
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :mentions, class_name: "Mention", foreign_key: "mentioned_user"
  has_many :statuses
  #a fan has idols/celebs and a celeb has fans
  has_many :fan_relationships, class_name: "Relationship", foreign_key: "fan_id"
  has_many :celeb_relationships, class_name: "Relationship", foreign_key: "celebrity_id"

  has_many :followers, through: :celeb_relationships, source: :fan
  has_many :celebs, through: :fan_relationships, source: :celebrity



  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :password, presence: true,  on: :create

  has_secure_password validations: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :creator?, :following?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    unless logged_in?
      flash[:notice] = "You must be logged in to access that page."
      redirect_to root_path
    end
  end

  def creator?(user)
    current_user == user
  end

  def following?(user)
    current_user.celebs.include?(user)
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @statuses = Status.where("body LIKE ?", "%##{params[:id]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome #{user.username}, you have logged in!"
      redirect_to statuses_path
    else
      flash[:notice] = "Your username or password is incorrect."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Bye, you have logged out."
    redirect_to new_user_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:edit,:update,:destroy, :show]
  before_action :require_logged_in
 
  def index
    @status = Status.new
    @statuses = []
    @statuses << current_user.statuses
    current_user.celebs.each do |celeb|
      @statuses << celeb.statuses
    end
    @statuses.flatten!
    @statuses.sort! { |a, b|  a.created_at <=> b.created_at }
  end

  def show
    
  end
 
  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    @status.creator = User.find(current_user)

    if @status.save
      flash[:notice] = "status has been created."
      redirect_to statuses_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @status.update(status_params)
      flash[:notice] = "Status has been updated"
      redirect_to statuses_path
    else
      render :edit
    end
  end

  def destroy
    @status.destroy
    flash[:notice] = "Status has been deleted."
    redirect_to user_path(current_user)
  end

  def mentions
    @mentions = current_user.mentions
  end

  def retweet
    status = Status.find(params[:id])
    Status.create(body: status.body, user_id: current_user.id, parent_status: status)
    flash[:notice] = "Your retweet has been submitted."
    redirect_to statuses_path

  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_logged_in, only: [:index, :show, :edit, :update, :follow, :unfollow]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @status = Status.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :index
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User has been updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follow
    celeb = User.find(params[:id])
    if celeb && !following?(celeb)
      current_user.celebs << celeb
      flash[:notice] = "You are following #{celeb.username}."
      redirect_to statuses_path
    else
      flash[:error] = "There was an error."
      redirect_to statuses_path
    end
  end

  def unfollow
      celeb = User.find(params[:id])
      relation = Relationship.find_by(celebrity: celeb, fan: current_user)
    if relation
      relation.delete
      flash[:notice] = "You have unfollowed #{celeb.username}."
      redirect_to statuses_path
    else
      flash[:error] = "There was an error."
      redirect_to :back
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params[:user][:username].downcase!
    params.require(:user).permit(:username,:password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_date(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end

  def auto_links(status)
    body = mentions_link(status)
    hashtag_link(body)
    return body
  end

  def mentions_link(status)
    if !status.mentions.empty?
      mention_names = []
      status.mentions.each do |mention|
        user = User.find(mention.mentioned_user)
        mention_names << user
      end
      temp = status.body
      mention_names.each do |user| 
        temp.gsub!("@#{user.username}", "#{link_to('@'<<user.username, user_path(user.id))}")
      end
      return temp
    else
      return status.body
    end
  end

  def hashtag_link(body)
    body.gsub!(/#(\S+)/, "<a href='/hashtags/\\1'>#\\1</a>")
  end

end

app/views/hashtags/show.html.erb
<br/>
<br/>
<div class="background">
  <div class="profile-background">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-3 my-tweets well your-tweets">
        <h2>#<%= params[:id] %></h2>
      </div>
    </div>
    <%= render 'statuses/statuses', statuses: @statuses %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="flasher flash-center alert alert-<%= name == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="birdy" src="/twitter.png">
      </a>
      <a class="navbar-brand" href="#">Twitter</a>
      <% if logged_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to "Dashboard", statuses_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Mentions", mentions_path %></li>
      </ul>
      <% end %>
    </div>
  <% if logged_in? %>
    <div class="pull-right">
      <ul class="nav navbar-nav" id="ul_nav">
        <li class="navbar-right"><%= link_to "New Tweet", new_status_path %></li>
        <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></a></li>
          </ul>
        </li>
      </ul>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>
<%= yield %>
<div id="footer"></div>
</body>
</html>

app/views/shared/_form_error.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
  </ul>
<% end %>

app/views/shared/_header.html.erb
<h2><%= header %></h2>
<hr/>

app/views/statuses/_form.html.erb
<%= render 'shared/form_error', obj: @status %>


<div class="profile-background container-fluid">
  <div class="row">
    <div class="col-md-2 col-xs-2"></div>
    <div class="col-md-8 col-xs-8 my-tweets well">
      <h2>New Status</h2>
      <hr/>
      <%= form_for(@status, class: "form-horizontal") do |f| %>  
        <div class="form-group">
          <%= f.label :body, class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_area :body, placeholder: "tweet something",class: "form-control" %>
          </div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Tweet it", class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>    
  </div>
</div>

app/views/statuses/_status.html.erb
    <div class="row">
      <div class="col-md-2 col-xs-2"></div>
      <div class="col-md-8 col-xs-8 my-tweets well">
        <h4>
        <% if status.parent_status.nil? %>
          <%= link_to status.creator.username, user_path(status.creator) %> 
        <% else %>
          <%= link_to status.parent_status.creator.username, status_path(status.parent_status) %>   (*retweeted* by <%= link_to status.creator.username, user_path(status.creator) %>) 
        <% end %>
          <small>- <%= display_date(status.created_at) %></small>
        </h4>
        <div class="well">
          <p><%= auto_links(status).html_safe %></p>
        </div>
        
        <small>
          <% if creator?(status.creator) %>
            <%= link_to edit_status_path(status) do%>
              <i class="glyphicon glyphicon-edit"></i>
              Edit
              <% end %>
            &nbsp;&nbsp;   
            <%= link_to status_path(status), method: :delete do %>
              <i class="glyphicon glyphicon-trash"></i>
              Delete
            <% end %>
          <% else %>
            &nbsp;&nbsp;   
            <%= link_to retweet_status_path(status), method: :post do %>
              <i class="glyphicon glyphicon-send"></i>
              Retweet
            <% end %>
          <% end %>
        </small>
      </div>
    </div>

app/views/statuses/_statuses.html.erb
<div class="container-fluid">
  <% statuses.reverse.each do |status| %>
    <%= render 'statuses/status', status: status %>
  <% end %>  
</div>

app/views/statuses/edit.html.erb
<h2>Edit Status</h2>
<hr/>
<%= render 'form' %>

app/views/statuses/index.html.erb
<br/>
<br/>
<div class="background">
  <%= render 'form' %>
  <div class="profile-background">
    <%= render 'statuses', statuses: @statuses %>
  </div>
</div>

app/views/statuses/mentions.html.erb
<br/>
<br/>
<div class="background">
  <div class="profile-background">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-3 my-tweets well your-tweets">
          <h2>Mentions</h2>
        </div>
      </div>
      <% @mentions.reverse.each do |mention| %>
        <%= render 'statuses/status', status: mention.status %>
      <% end %>  
    </div>
  </div>
</div>

app/views/statuses/new.html.erb
<div class="background">
  <br/>
  <br/>
  <%= render 'form' %>
</div>

app/views/statuses/show.html.erb
<br/>
<br/>
<br/>
<div class="background">
  <div class="profile-background">
    <div class="container-fluid">
      <%= render 'statuses/status', status: @status %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/form_error', obj: @user %>

<%= form_for(@user, class: "form-horizontal") do |f| %>
<div class="form-group">
  <%= f.label :username, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :username, placeholder: "Username",class: "form-control" %>
  </div>
</div>
<br/>
<br/>
<div class="form-group">
  <%= f.label :email, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :email, placeholder: "Username",class: "form-control" %>
  </div>
</div>
<br/>
<br/>
<div class="form-group">
  <%= f.label :password, class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.password_field :password, placeholder: "Username",class: "form-control" %>
  </div>
</div>
<br/>
<br/>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Register", class: 'btn btn-success' %>
  </div>
</div>
<% end %>

app/views/users/_users.html.erb
<% users.each do |user| %>
  <div class="row">
    <div class="col-md-9 col-xs-8">
      <strong><%= user.username %></strong>
    </div>
    <div class="col-md-3 col-xs-4">
      <small>
        <%= link_to user_path(user) do%>
          <i class="glyphicon glyphicon-user"></i>
          Profile
        <% end %>
        &nbsp;&nbsp;  
        <% if user != current_user %>
        <% if !following?(user) %>
        <%= link_to "Follow", follow_user_path(user), method: :post, class: "btn btn-success" %>
        <% else %>
          <%= link_to "Unfollow", unfollow_user_path(user), method: :delete, class: "btn btn-info" %>
        <% end %>
        <% end %>
      </small>              
    </div>
  </div>
  <hr/>
<% end %>

app/views/users/edit.html.erb
<div class="background"> 
  <div class="profile-background container-fluid">
    <br/>
    <br/>
    <div class="row">
      <div class="col-md-2 col-xs-2"></div>
      <div class="col-md-8 col-xs-8 my-tweets well">
        <h2>Edit Account</h2>
        <hr/>
        <%= render 'form' %>
      </div>    
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br/>
<br/>
<div class="background">
  <div class="profile-background">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 col-xs-2"></div>
        <div class="col-md-8 col-xs-8 well my-tweets">
          <h2>Users</h2>
          <hr/>
          <%= render 'users', users: @users %>
        </div>    
      </div>
    </div>  
  </div>  
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 col-xs-2 pull-right"></div>
      <div class="col-md-4 col-xs-4 pull-right">
        <div class="well box-me">
          <h3>Login</h3>
          <%= render 'sessions/form' %>
        </div>              
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-xs-4 pull-right">
        <div class="well box-me register">
          <h3>New to Twitter?</h3>
          <h4 style="margin-bottom: 8px;">sign up</h4>
          <%= render 'form' %>
        </div>              
      </div>
    </div>
  </div>  
</div>

app/views/users/show.html.erb
<div class="blue-rect">
  <div class="propic-container">
        <img alt="propic" src="/me.jpg" class="propic-img">
  </div>
</div>

<div class="profile_nav">
  <h3 id="profile-name">@<%= @user.username %></h3>

  <div class="profile-center">
    <ul class="nav nav-tabs">
      <li role="presentation" class="<%= 'active' if params[:tab].nil? %>">
        <%= link_to "Tweets(#{@user.statuses.size})", user_path(@user) %>
      </li>
      <% if creator?(@user) %>
        <li role="presentation" class="<%= 'active' if params[:tab] == 'Following'%>">
          <%= link_to "Following(#{@user.celebs.size})", user_path(@user, tab: "Following") %>
        </li>
      <% end %>
      <li role="presentation" class="<%= 'active' if params[:tab] == 'Followers' %>">
        <%= link_to "Followers(#{@user.followers.size})", user_path(@user, tab: "Followers") %>
      </li>
    </ul>
  </div>
  <div class=" profile-edit-button">
    <% if creator?(@user) %>
        <%= link_to "Edit Account", edit_user_path(@user), class: "btn btn-default" %>
    <% else %>
      <% if !following?(@user) %>
        <%= link_to "Follow", follow_user_path(@user), method: :post, class: "btn btn-success" %>
      <% else %>
        <%= link_to "Unfollow", follow_user_path(@user), method: :delete, class: "btn btn-info" %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="background">
<div class="profile-background">
  <div class="container-fluid">
    <% if params[:tab].nil? %>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-3 my-tweets well your-tweets">
          <h2><%= @user.username %>'s' Tweets</h2>
        </div>
      </div>
        <%= render 'statuses/statuses', statuses: @user.statuses %>
    <% elsif params[:tab] == "Followers" %>
          <div class="row">
            <div class="col-md-2 col-xs-2"></div>
            <div class="col-md-8 col-xs-8 well my-tweets">
              <h2>Followers</h2>
              <hr/>
              <%= render 'users', users: @user.followers %>
            </div>  
          </div>

    <% elsif params[:tab] == "Following" %>
          <div class="row">
            <div class="col-md-2 col-xs-2"></div>
            <div class="col-md-8 col-xs-8 well my-tweets">
              <h2>Following</h2>
              <hr/>
              <%= render 'users', users: @user.celebs %>
            </div>  
          </div>
    <% end %>
  </div>
</div>
</div>